"""Broker adapter protocol and helpers.

TigerBroker implementation is loaded lazily to avoid importing tigeropen
at module level. MockBroker in tests/ provides a test double.
"""
import logging
from typing import Protocol, runtime_checkable

logger = logging.getLogger(__name__)


@runtime_checkable
class BrokerAdapter(Protocol):
    """Methods the IC pipeline calls on any broker."""

    def get_option_analysis(self, symbols: list[str]) -> list: ...
    def get_stock_price(self, symbol: str) -> float: ...
    def get_option_expirations(self, symbol: str) -> list[dict]: ...
    def get_option_chain(self, symbol: str, expiry: str, option_filter: dict | None = None) -> list[dict]: ...
    def get_option_briefs(self, identifiers: list[str]) -> list: ...
    def place_option_market_order(self, identifier: str, action: str, quantity: int) -> int: ...
    def get_order(self, order_id: int) -> object: ...
    def cancel_order(self, order_id: int) -> None: ...
    def get_open_orders(self, sec_type: str = "OPT") -> list: ...
    def get_assets(self) -> object: ...
    def get_positions(self, sec_type: str = "OPT") -> list: ...
